[tool.mypy]
python_version = "3.9"
strict = true
warn_unused_configs = true
warn_unused_ignores = true

[tool.yapf]
column_limit = 100
continuation_align_style = "space"
coalesce_brackets = true
indent_dictionary_value = true
